### ISSUE TITLE
report zero until performing echo calls?

### ISSUE THREAD

**Issue by tghoward** [cjo20/EdisonVoltage#2]
Not sure the cause of this, but my edison was reporting 0%, even when plugged in and charging, until I manually called the echo commands noted in your README.   It was working fine a few days ago so I'm not sure what caused it to stop reporting. I guess this is really just an fyi. 

As follows:

> edison@bcb-edison3:~/src/EdisonVoltage$ ./voltage
> Raw Value: 0
> Battery Voltage: 0mV (-66%)
> edison@bcb-edison3:~/src/EdisonVoltage$ cat /sys/devices/platform/bcove_adc/basincove_gpadc/result
> sample_result[0] = 0
> sample_result[1] = 0
> sample_result[2] = 0
> sample_result[3] = 0
> sample_result[4] = 0
> sample_result[5] = 0
> sample_result[6] = 0
> sample_result[7] = 0
> sample_result[8] = 0
> edison@bcb-edison3:~/src/EdisonVoltage$ echo 0x1 | sudo tee /sys/devices/platform/bcove_adc/basincove_gpadc/channel
> [sudo] password for edison: 
> 0x1
> edison@bcb-edison3:~/src/EdisonVoltage$ echo 1 | sudo tee /sys/devices/platform/bcove_adc/basincove_gpadc/sample
> 1
> edison@bcb-edison3:~/src/EdisonVoltage$ cat /sys/devices/platform/bcove_adc/basincove_gpadc/result
> sample_result[0] = 949
> sample_result[1] = 0
> sample_result[2] = 0
> sample_result[3] = 0
> sample_result[4] = 0
> sample_result[5] = 0
> sample_result[6] = 0
> sample_result[7] = 0
> sample_result[8] = 0
> edison@bcb-edison3:~/src/EdisonVoltage$ ./voltage
> Raw Value: 949
> Battery Voltage: 4170mV (99%)

**Comment by cjo20** [comment]
The `voltage` command must be run as root; writing to `/sys/devices/platform/bcove_adc/basincove_gpadc/sample` and `/sys/devices/platform/bcove_adc/basincove_gpadc/channel` both require root permissions. When you run `./voltage` without being root, it only picks up the value the last time the sample was actually run.

**Comment by tghoward** [comment]
Ah, ok, thanks.
